/**
 * Created by linming on 15-3-1.
 */
public enum VoideCommandKey {
    CREATE_File, SAVE_FILE, ADD_CLASS, ADD_ITEM, ADD_INSTANCE, DELETE_SELECTED, SELECT_CLASS, SELECT_ITEM, RENAME, SELECT, CHOICE_CLASS_TYPE, UP_CLASS_POOL, START, SELECT_MODEL, CHANGE_ID, CHANGE_VALUE, CHANGE_ANNOTATION, EXPORT_EXCEL, LOAD_SET, IMPORT, IMPORT_EXCEL, EXPORT_JSON, EXPORT_LUA, OPEN_File
}
